name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-qemu-action@v1

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Docker build and push
      env:
        DOCKER_TLS_CERTDIR: "/certs"
      run: |
        echo "Criando as imagens..."
        docker build -t carlosfalcone/projeto2-backfront:%TAG_BACKFRONT% app/.
        docker build -t carlosfalcone/projeto2-database:%TAG_DATABASE% database/. 

        echo "Realizando o push das imagens..."
        docker push carlosfalcone/projeto2-backfront:%TAG_BACKFRONT%
        docker push carlosfalcone/projeto2-database:%TAG_DATABASE%


# O codigo abaixo nao funcionou no computador fisico local (windows)
  # kubernetes_deploy:
  #   needs: [build-linux]  # Dependente do job build-linux
  #   runs-on: self-hosted

  #   steps:
  #   - name: Checkout do código
  #     uses: actions/checkout@v2
      
  #   - name: Configurar PowerShell
  #     run: |
  #       Set-Location -Path C:\Users\Falcone\Downloads\k8s-projeto2-cicd
  #       .\script-kubernetes-win.bat
  #     shell: powershell
