apiVersion: v1
kind: Service
metadata:
  name: app1-service # Nome alterado de php-service para app1-service
spec:
  selector:
    app: app1
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
      